language: python
virtualenv:
  system_site_packages: true
python:
  - "2.7"
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install nose coverage
  - pip install coveralls
script:
  - python setup.py nosetests --processes=20 --process-timeout=200 --verbosity 2 --with-coverage --cover-package itur  
after_sucess:
  coveralls
after_failure:
  coveralls