language: python
os:
  - linux
  - osx
  - windows  
virtualenv:
  system_site_packages: true
python:
  - "2.7"
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install nose coverage
  - pip install coveralls
script:
  - python setup.py nosetests --with-coverage --cover-package itur  
after_sucess:
  coveralls